# Generated by Django 3.2.6 on 2021-08-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210827_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
